<?php
// auto-generated by sfRoutingConfigHandler
// date: 2009/05/12 04:13:50
return array(
'type_operation' => new sfPropelRouteCollection(array (
  'model' => 'TypeOperation',
  'module' => 'type_operation',
  'prefix_path' => 'type_operation',
  'column' => 'id',
  'with_wildcard_routes' => true,
  'name' => 'type_operation',
  'requirements' => 
  array (
  ),
)),
'employe' => new sfPropelRouteCollection(array (
  'model' => 'Employe',
  'module' => 'employe',
  'prefix_path' => 'employe',
  'column' => 'id',
  'with_wildcard_routes' => true,
  'name' => 'employe',
  'requirements' => 
  array (
  ),
)),
'garage' => new sfPropelRouteCollection(array (
  'model' => 'Garage',
  'module' => 'garage',
  'prefix_path' => 'garage',
  'column' => 'id',
  'with_wildcard_routes' => true,
  'name' => 'garage',
  'requirements' => 
  array (
  ),
)),
'modele' => new sfPropelRouteCollection(array (
  'model' => 'Modele',
  'module' => 'modele',
  'prefix_path' => 'modele',
  'column' => 'id',
  'with_wildcard_routes' => true,
  'name' => 'modele',
  'requirements' => 
  array (
  ),
)),
'marque' => new sfPropelRouteCollection(array (
  'model' => 'Marque',
  'module' => 'marque',
  'prefix_path' => 'marque',
  'column' => 'id',
  'with_wildcard_routes' => true,
  'name' => 'marque',
  'requirements' => 
  array (
  ),
)),
'homepage' => new sfRoute('/', array (
  'module' => 'main',
  'action' => 'index',
), array (
), array (
)),
'default_index' => new sfRoute('/:module', array (
  'action' => 'index',
), array (
), array (
)),
'default' => new sfRoute('/:module/:action/*', array (
), array (
), array (
)),
);
